- "CREATE TABLE `test_table` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_test_table_email` (`email`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin"
- "ALTER TABLE `test_table` ADD COLUMN `status` varchar(20) DEFAULT 'active'"
- "ALTER TABLE `test_table` ADD INDEX `idx_test_table_status` (`status`)"
- "DROP TABLE IF EXISTS `old_test_table`"
- "ALTER TABLE small_table ADD INDEX idx_name (name)"
- "ALTER TABLE small_table ADD COLUMN discount_rate DECIMAL(5,2) DEFAULT 0.00"
- "ALTER TABLE large_table ADD COLUMN discount_rate DECIMAL(5,2) DEFAULT 0.00"
- "ALTER TABLE large_table MODIFY COLUMN description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
