version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: alterguard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  pt-toolkit:
    image: perconalab/percona-toolkit:latest
    container_name: alterguard-pt-toolkit
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    environment:
      DATABASE_DSN: "testuser:testpassword@tcp(mysql:3306)/testdb"

  alterguard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alterguard-app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      DATABASE_DSN: "testuser:testpassword@tcp(mysql:3306)/testdb"
      SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/dummy/webhook/url"
    command: tail -f /dev/null

volumes:
  mysql_data:
