services:
  mysql:
    image: mysql:8
    container_name: alterguard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  pt-toolkit:
    # amd64 version
    #image: perconalab/percona-toolkit:latest
    image: perconalab/percona-toolkit:3.7.0-aarch64
    container_name: alterguard-pt-toolkit
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    environment:
      DATABASE_DSN: "testuser:testpassword@tcp(mysql:3306)/testdb"
volumes:
  mysql_data:
